Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/xenial64"
    config.vm.network "forwarded_port", guest:80, host:8080
    config.vm.synced_folder "./web", "/var/www/", create: true
	config.vm.synced_folder "./mysql", "/var/lib/mysql", create: true
    config.vm.provider "virtualbox" do |vb|
        vb.memory = "512" 
    end
	mysql_root_password = "vagrant"
    config.vm.provision "shell", inline: <<-SHELL
        sudo apt-get update
        sudo apt-get install apache2 -yq
        sudo apt-get install php php-gettext libapache2-mod-php -yq
		
        sudo debconf-set-selections <<< "mysql-server mysql-server/root_password password #{mysql_root_password}"
		sudo debconf-set-selections <<< "mysql-server mysql-server/root_password_again password #{mysql_root_password}"
		sudo apt-get -yq install mysql-server

		sudo debconf-set-selections <<< "phpmyadmin phpmyadmin/internal/skip-preseed boolean true"
		sudo debconf-set-selections <<< "phpmyadmin phpmyadmin/reconfigure-webserver multiselect apache2"
		sudo debconf-set-selections <<< "phpmyadmin phpmyadmin/dbconfig-install boolean false"
		sudo apt-get -yq install phpmyadmin
		
        sudo service apache2 restart
    SHELL
end
