version: '3.8'
services:

  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "m300"
      MYSQL_DATABASE: "nextcloud"
      MYSQL_USER: "nextcloud"
      MYSQL_PASSWORD: "m300"

  app:
    image: nextcloud
    ports:
      - 8080:80
    volumes:
      - ./nextcloud:/var/www/html
    restart: always
    environment: 
        MYSQL_HOST: "db"
        MYSQL_DATABASE: "nextcloud"
        MYSQL_USER: "nextcloud"
        MYSQL_PASSWORD: "m300"
        NEXTCLOUD_ADMIN_USER: "admin"
        NEXTCLOUD_ADMIN_PASSWORD: "m300"

