Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/xenial64"
    config.vm.network "forwarded_port", guest:80, host:8080
    config.vm.synced_folder "./web", "/var/www/", create: true
    config.vm.synced_folder "./apache", "/etc/apache2", create: true
    config.vm.provider "virtualbox" do |vb|
        vb.memory = "512" 
    end
    config.vm.provision "shell", inline: <<-SHELL
        sudo apt-get update
        sudo apt-get install apache2 -y
        sudo apt-get install libxml2-dev -y
        sudo a2enmod proxy
        sudo a2enmod proxy_html
        sudo a2enmod proxy_http
        sudo service apache2 restart
    SHELL
end
