Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/xenial64"
    config.vm.network "forwarded_port", guest:80, host:8080
    config.vm.synced_folder ".", "/var/www/"
    config.vm.provider "virtualbox" do |vb|
        vb.memory = "512" 
    end
    config.vm.provision "shell", inline: <<-SHELL
        sudo apt-get update
        sudo apt-get install ufw -y
    SHELL
end
